/**
 * Incident Management Engine for SignalBridge
 * Features:
 * - Deterministic code-generated incident titles (Zero AI calls)
 * - Stage-1 routing integration for department assignment
 * - One incident per episode with deduplicated complaint attachment
 * - Comprehensive ActivityEntry audit trail
 */

import { Alert, Incident, ActivityEntry, Complaint, IncidentStatus } from "../types";
import { TELECOM_CATEGORIES } from "../sectors/telecom";
import { calculateRouting } from "./routing";
import { calculatePriority } from "./priority";

export interface IncidentProcessResult {
  incidents: Incident[];
  createdIncident?: Incident;
  updatedIncident?: Incident;
}

/**
 * Creates a new incident from a trigger alert or attaches to an existing active incident for that key.
 * Title is strictly generated by code: `${categoryDisplayName} spike in ${districtName}`
 */
export function handleAlertIncident(
  alert: Alert,
  complaintsMap: Map<string, Complaint>,
  existingIncidents: Incident[],
  currentSimTime: number,
  episodeIncidentId?: string
): IncidentProcessResult {
  const category = alert.key.category;
  const district = alert.key.district;
  const categoryMeta = TELECOM_CATEGORIES[category];
  const categoryDisplayName = categoryMeta?.displayName || category;

  // Check if an existing open incident matches this episode or key
  const existingIncident = existingIncidents.find(
    (inc) =>
      (episodeIncidentId && inc.id === episodeIncidentId) ||
      (inc.category === category &&
        inc.district === district &&
        inc.status !== "Resolved")
  );

  // Compute average severity across alert complaints
  const alertComplaints = alert.complaintIds
    .map((id) => complaintsMap.get(id))
    .filter((c): c is Complaint => !!c && !!c.analysis);

  const avgSeverity =
    alertComplaints.length > 0
      ? alertComplaints.reduce((acc, c) => acc + (c.analysis?.severity || 1), 0) /
        alertComplaints.length
      : 2;

  // Determine priority via code heuristics
  const priorityDecision = calculatePriority({
    category,
    zScore: alert.zScore,
    count: alert.count,
    avgSeverity,
    isAlert: true,
  });

  // Calculate destination department via pure Stage-1 routing table
  const routeDecision = calculateRouting({
    category,
    confidence: 0.95,
    needsManualReview: false,
    containsInstructionsToSystem: false,
    source: "live_ai",
  });

  // Timestamps
  const earliestComplaintTime =
    alertComplaints.length > 0
      ? Math.min(...alertComplaints.map((c) => c.ts))
      : currentSimTime;

  if (existingIncident) {
    // ATTACH TO EXISTING INCIDENT & DEDUPLICATE
    const existingSet = new Set(existingIncident.complaintIds);
    const trulyNewIds: string[] = [];

    for (const id of alert.complaintIds) {
      if (!existingSet.has(id)) {
        existingSet.add(id);
        trulyNewIds.push(id);
      }
    }

    if (trulyNewIds.length === 0) {
      // Nothing new to attach
      return { incidents: existingIncidents };
    }

    const updatedComplaintIds = Array.from(existingSet);

    // Recalculate priority if count increased
    const updatedPriorityDecision = calculatePriority({
      category,
      zScore: alert.zScore,
      count: updatedComplaintIds.length,
      avgSeverity,
      isAlert: true,
    });

    const isSurgeDuringMonitoring = existingIncident.status === "Monitoring";
    const nextStatus = isSurgeDuringMonitoring ? "Reopened" : existingIncident.status;

    const attachActivity: ActivityEntry = {
      ts: currentSimTime,
      actor: "system",
      action: isSurgeDuringMonitoring ? "Incident Reopened" : "Complaints attached",
      details: isSurgeDuringMonitoring
        ? `Complaint surge detected above alert threshold during Monitoring (${alert.count} complaints, Z-score=${alert.zScore.toFixed(
            2
          )}). Reopened for investigation.`
        : `Attached ${trulyNewIds.length} new complaint(s) from ongoing episode. Total attached: ${updatedComplaintIds.length}.`,
    };

    const updatedIncident: Incident = {
      ...existingIncident,
      status: nextStatus,
      complaintIds: updatedComplaintIds,
      priority: updatedPriorityDecision.priority,
      activityLog: [...existingIncident.activityLog, attachActivity],
    };

    const newIncidentsList = existingIncidents.map((inc) =>
      inc.id === existingIncident.id ? updatedIncident : inc
    );

    return {
      incidents: newIncidentsList,
      updatedIncident,
    };
  }

  // Check if a resolved incident exists for this key (reopen on new alert after cooldown)
  const resolvedIncident = existingIncidents.find(
    (inc) => inc.category === category && inc.district === district && inc.status === "Resolved"
  );

  if (resolvedIncident) {
    const existingSet = new Set(resolvedIncident.complaintIds);
    for (const id of alert.complaintIds) {
      existingSet.add(id);
    }
    const updatedComplaintIds = Array.from(existingSet);

    const reopenActivity: ActivityEntry = {
      ts: currentSimTime,
      actor: "system",
      action: "Incident Reopened",
      details: `New alert arrived after resolution and cooldown (${alert.count} complaints, Z-score=${alert.zScore.toFixed(
        2
      )}). Reopened for investigation.`,
    };

    const reopenedIncident: Incident = {
      ...resolvedIncident,
      status: "Reopened",
      complaintIds: updatedComplaintIds,
      priority: priorityDecision.priority,
      activityLog: [...resolvedIncident.activityLog, reopenActivity],
    };

    const newIncidentsList = existingIncidents.map((inc) =>
      inc.id === resolvedIncident.id ? reopenedIncident : inc
    );

    return {
      incidents: newIncidentsList,
      updatedIncident: reopenedIncident,
    };
  }

  // CREATE NEW INCIDENT (Zero AI call for title)
  const incidentTitle = `${categoryDisplayName} spike in ${district}`;
  const incidentId =
    episodeIncidentId ||
    `INC-${currentSimTime.toString(36).toUpperCase()}-${Math.floor(
      Math.random() * 1000
    )}`;

  // Deduplicate initial complaint IDs
  const uniqueComplaintIds = Array.from(new Set(alert.complaintIds));

  const initialActivity: ActivityEntry = {
    ts: currentSimTime,
    actor: "system",
    action: "Incident created",
    details: `Triggered by alert ${alert.id} (${alert.count} complaints, Z-score=${alert.zScore.toFixed(
      2
    )}). Priority: ${priorityDecision.priority} (${priorityDecision.heuristicRule}). Routed to ${routeDecision.department}.`,
  };

  const newIncident: Incident = {
    id: incidentId,
    title: incidentTitle,
    category,
    district,
    status: "New",
    priority: priorityDecision.priority,
    department: routeDecision.department,
    createdAt: currentSimTime,
    firstComplaintAt: earliestComplaintTime,
    complaintIds: uniqueComplaintIds,
    alertId: alert.id,
    activityLog: [initialActivity],
  };

  return {
    incidents: [newIncident, ...existingIncidents],
    createdIncident: newIncident,
  };
}

/**
 * Strict Stage 3 State Machine Transition Map
 * Allowed transitions only:
 * New -> Assigned -> Investigating -> Action Taken -> Monitoring -> Resolved.
 * Reopened -> Investigating only.
 */
export const ALLOWED_TRANSITIONS: Record<IncidentStatus, IncidentStatus[]> = {
  New: ["Assigned"],
  Assigned: ["Investigating"],
  Investigating: ["Action Taken"],
  "Action Taken": ["Monitoring"],
  Monitoring: ["Resolved", "Reopened"],
  Resolved: ["Reopened"],
  Reopened: ["Investigating"],
};

export function getAllowedNextStatuses(status: IncidentStatus): IncidentStatus[] {
  return ALLOWED_TRANSITIONS[status] || [];
}

export function canTransition(current: IncidentStatus, target: IncidentStatus): boolean {
  const allowed = ALLOWED_TRANSITIONS[current] || [];
  return allowed.includes(target);
}

/**
 * Executes a verified state machine transition and records an ActivityEntry.
 */
export function transitionIncidentStatus(
  incident: Incident,
  targetStatus: IncidentStatus,
  actor: "system" | "department" | "analyst",
  reason: string,
  currentTime: number
): { success: boolean; incident: Incident; error?: string } {
  if (!canTransition(incident.status, targetStatus)) {
    return {
      success: false,
      incident,
      error: `Invalid transition: cannot advance from "${incident.status}" to "${targetStatus}". Allowed next: ${getAllowedNextStatuses(
        incident.status
      ).join(", ") || "None"}`,
    };
  }

  const activity: ActivityEntry = {
    ts: currentTime,
    actor,
    action: `Status changed to ${targetStatus}`,
    details: reason || `Transitioned from ${incident.status} to ${targetStatus}`,
  };

  const updatedIncident: Incident = {
    ...incident,
    status: targetStatus,
    activityLog: [...incident.activityLog, activity],
  };

  return {
    success: true,
    incident: updatedIncident,
  };
}

/**
 * Assigns an owner (free-text) and advances to "Assigned" if currently "New".
 */
export function assignIncidentOwner(
  incident: Incident,
  ownerName: string,
  actor: "system" | "department" | "analyst",
  currentTime: number
): Incident {
  const cleanOwner = ownerName.trim();
  const activity: ActivityEntry = {
    ts: currentTime,
    actor,
    action: "Owner assigned",
    details: `Owner assigned to "${cleanOwner || "Unassigned"}"`,
  };

  let nextStatus = incident.status;
  if (incident.status === "New" && cleanOwner.length > 0) {
    nextStatus = "Assigned";
  }

  return {
    ...incident,
    owner: cleanOwner || undefined,
    status: nextStatus,
    activityLog: [...incident.activityLog, activity],
  };
}

